services:
  web:
    build:
      context: .
      target: builder
    ports:
      - 8100:8100
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
